version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
    volumes:
      #- ./urban-explorer:/app
      - ./prisma:/app/prisma  # Persist the Prisma database file (dev.db) here
    depends_on: []
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
